//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class companytable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public companytable()
        {
            this.vehicletable = new HashSet<vehicletable>();
        }
    
        public int companynumber { get; set; }
        public string companyname { get; set; }
        public string city { get; set; }
        public Nullable<int> addressnumber { get; set; }
        public Nullable<int> vehiclecount { get; set; }
        public Nullable<int> rate { get; set; }
    
        public virtual addresstable addresstable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehicletable> vehicletable { get; set; }
    }
}
