//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicletable
    {
        public int vehiclenumber { get; set; }
        public string name { get; set; }
        public string model { get; set; }
        public Nullable<int> licenseage { get; set; }
        public Nullable<int> minumumagelimit { get; set; }
        public Nullable<int> dailykmlimit { get; set; }
        public Nullable<int> currentkm { get; set; }
        public Nullable<bool> airbag { get; set; }
        public Nullable<double> trunkvolume { get; set; }
        public Nullable<int> seatcount { get; set; }
        public Nullable<double> dailyrentprice { get; set; }
        public Nullable<int> companynumber { get; set; }
    
        public virtual companytable companytable { get; set; }
    }
}
